Repository strangerstudios/pmpro-member-directory, pull requests merged in 2022-03, with the labels that each got.

#101 Pretty Permalinks for Profiles
  pmpro-member-directory.php
  templates/directory.php
  templates/profile.php
Labels: Type: Enhancement

#91 Update directory.php to correct search bug
  templates/directory.php
Labels: Type: Bug, Impact: Low, Difficulty: Easy

#99 pmpro_get_element_class Implemented
  templates/directory.php
  templates/profile.php
Labels: Type: Enhancement

#100 Filter added to directory search query
  templates/directory.php
Labels: Type: Enhancement

#104 Numbered Pagination Added
  css/pmpro-member-directory.css
  templates/directory.php
Labels: Type: Enhancement

#105 Profile title filtering adjusted to not reflect in menu
  templates/profile.php
Labels: Type: Bug

#106 Filter fields based on level
  pmpro-member-directory.php
  templates/directory.php
Labels: Type: Enhancement

#82 Filter added to directory attributes
  templates/directory.php
Labels: Type: Enhancement

#89 Enhancement/Fix: Update Localization
  .gitignore
  includes/localization.php
  languages/pmpro-fr_FR.po
  languages/pmpro-member-directory-fr_FR.mo
  languages/pmpro-member-directory-fr_FR.po
  languages/pmpro-member-directory.mo
  languages/pmpro-member-directory.po
  languages/pmpro-member-directory.pot
  pmpro-member-directory.php
  templates/directory.php
  templates/profile.php
Labels: Type: Enhancement

#102 Adds an Edit Profile link to the admin bar
  pmpro-member-directory.php
Labels: Type: Enhancement

#107 Filter the user identifier
  pmpro-member-directory.php
  templates/directory.php
  templates/profile.php
Labels: Type: Enhancement
